spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loan_management_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security:
  jwt:
    issuer: loan-manager
    access-token-validity: 900000 # 15 minutes
    refresh-token-validity: 604800000 # 7 days
    secret: YourSuperSecretJWTKeyThatIsAtLeast32CharactersLongForHS256Algorithm

management:
  endpoints:
    web:
      exposure:
        include: health,info
